version: '3.8'

services:
  bot:
    build: .
    container_name: my_finance_bot
    restart: unless-stopped
    ports:
      - "8080:8080"  # <-- ПРОПИШИ ЦЕЙ РЯДОК, якщо його немає
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1