# Статична база продуктів для ініціалізації БД при першому запуску
DEFAULT_FOOD_CATALOG = [
    # Білки (1 порція ≈ 35 г білка)
    {"category": "protein", "name": "Куряче філе", "portion_size": 160.0, "unit": "г"},
    {"category": "protein", "name": "Стегно курки без шкіри", "portion_size": 110.0, "unit": "г"},
    {"category": "protein", "name": "Філе індички", "portion_size": 160.0, "unit": "г"},
    {"category": "protein", "name": "Стегно індички без шкіри", "portion_size": 110.0, "unit": "г"},
    {"category": "protein", "name": "Телятина", "portion_size": 150.0, "unit": "г"},
    {"category": "protein", "name": "Вирізка свинини", "portion_size": 140.0, "unit": "г"},
    {"category": "protein", "name": "Печінка куряча", "portion_size": 170.0, "unit": "г"},
    {"category": "protein", "name": "Печінка яловича", "portion_size": 170.0, "unit": "г"},
    {"category": "protein", "name": "Хек", "portion_size": 190.0, "unit": "г"},
    {"category": "protein", "name": "Мінтай", "portion_size": 190.0, "unit": "г"},
    {"category": "protein", "name": "Тріска", "portion_size": 190.0, "unit": "г"},
    {"category": "protein", "name": "Судак", "portion_size": 190.0, "unit": "г"},
    {"category": "protein", "name": "Пікша", "portion_size": 190.0, "unit": "г"},
    {"category": "protein", "name": "Окунь", "portion_size": 190.0, "unit": "г"},
    {"category": "protein", "name": "Щука", "portion_size": 190.0, "unit": "г"},
    {"category": "protein", "name": "Тілапія", "portion_size": 190.0, "unit": "г"},
    {"category": "protein", "name": "Тунець у власному соку", "portion_size": 200.0, "unit": "г"},
    {"category": "protein", "name": "Лосось", "portion_size": 100.0, "unit": "г"},
    {"category": "protein", "name": "Форель", "portion_size": 100.0, "unit": "г"},
    {"category": "protein", "name": "Скумбрія", "portion_size": 100.0, "unit": "г"},
    {"category": "protein", "name": "Оселедець", "portion_size": 100.0, "unit": "г"},
    {"category": "protein", "name": "Сардина", "portion_size": 110.0, "unit": "г"},
    {"category": "protein", "name": "Тунець (жирний)", "portion_size": 100.0, "unit": "г"},
    {"category": "protein", "name": "Креветки", "portion_size": 180.0, "unit": "г"},
    {"category": "protein", "name": "Мідії без олії", "portion_size": 220.0, "unit": "г"},
    {"category": "protein", "name": "Восьминіг", "portion_size": 180.0, "unit": "г"},
    {"category": "protein", "name": "Курячі яйця", "portion_size": 3.0, "unit": "шт"},
    {"category": "protein", "name": "Сир кисломолочний 0%", "portion_size": 220.0, "unit": "г"},
    {"category": "protein", "name": "Сир кисломолочний 2%", "portion_size": 200.0, "unit": "г"},
    {"category": "protein", "name": "Сир кисломолочний 5%", "portion_size": 180.0, "unit": "г"},
    {"category": "protein", "name": "Сир твердий", "portion_size": 50.0, "unit": "г"},
    {"category": "protein", "name": "Грецький йогурт", "portion_size": 330.0, "unit": "г"},
    {"category": "protein", "name": "Йогурт до 3%", "portion_size": 330.0, "unit": "г"},
    {"category": "protein", "name": "Кефір до 3%", "portion_size": 400.0, "unit": "мл"},
    {"category": "protein", "name": "Молоко до 2.5%", "portion_size": 400.0, "unit": "мл"},

    # Вуглеводи (1 порція ≈ 40 г вуглеводів)
    {"category": "carbs", "name": "Рис", "portion_size": 50.0, "unit": "г"},
    {"category": "carbs", "name": "Гречка", "portion_size": 50.0, "unit": "г"},
    {"category": "carbs", "name": "Булгур", "portion_size": 50.0, "unit": "г"},
    {"category": "carbs", "name": "Кус-кус", "portion_size": 50.0, "unit": "г"},
    {"category": "carbs", "name": "Перловка", "portion_size": 50.0, "unit": "г"},
    {"category": "carbs", "name": "Ячна крупа", "portion_size": 50.0, "unit": "г"},
    {"category": "carbs", "name": "Пшоняна крупа", "portion_size": 50.0, "unit": "г"},
    {"category": "carbs", "name": "Вівсяні пластівці", "portion_size": 50.0, "unit": "г"},
    {"category": "carbs", "name": "Кукурудзяна крупа", "portion_size": 55.0, "unit": "г"},
    {"category": "carbs", "name": "Манка", "portion_size": 50.0, "unit": "г"},
    {"category": "carbs", "name": "Кіноа", "portion_size": 50.0, "unit": "г"},
    {"category": "carbs", "name": "Макарони", "portion_size": 50.0, "unit": "г"},
    {"category": "carbs", "name": "Цільнозернові макарони", "portion_size": 50.0, "unit": "г"},
    {"category": "carbs", "name": "Локшина", "portion_size": 50.0, "unit": "г"},
    {"category": "carbs", "name": "Лаваш", "portion_size": 70.0, "unit": "г"},
    {"category": "carbs", "name": "Цільнозерновий хліб", "portion_size": 70.0, "unit": "г"},
    {"category": "carbs", "name": "Житній хліб", "portion_size": 70.0, "unit": "г"},
    {"category": "carbs", "name": "Хлібці", "portion_size": 60.0, "unit": "г"},
    {"category": "carbs", "name": "Картопля", "portion_size": 225.0, "unit": "г"},
    {"category": "carbs", "name": "Батат", "portion_size": 225.0, "unit": "г"},
    {"category": "carbs", "name": "Кукурудза", "portion_size": 250.0, "unit": "г"},
    {"category": "carbs", "name": "Квасоля", "portion_size": 150.0, "unit": "г"},
    {"category": "carbs", "name": "Нут", "portion_size": 150.0, "unit": "г"},
    {"category": "carbs", "name": "Горох", "portion_size": 200.0, "unit": "г"},
    {"category": "carbs", "name": "Сочевиця", "portion_size": 70.0, "unit": "г"},

    # Жири (1 порція ≈ 15 г жиру)
    {"category": "fats", "name": "Будь-яка олія", "portion_size": 15.0, "unit": "г"},
    {"category": "fats", "name": "Авокадо", "portion_size": 80.0, "unit": "г"},
    {"category": "fats", "name": "Маслини", "portion_size": 50.0, "unit": "г"},
    {"category": "fats", "name": "Оливки", "portion_size": 50.0, "unit": "г"},
    {"category": "fats", "name": "Майонез", "portion_size": 20.0, "unit": "г"},
    {"category": "fats", "name": "Кетчуп", "portion_size": 50.0, "unit": "г"},
    {"category": "fats", "name": "Будь-які горіхи або насіння", "portion_size": 25.0, "unit": "г"},
    {"category": "fats", "name": "Арахісова паста", "portion_size": 25.0, "unit": "г"},
    {"category": "fats", "name": "Тахіні", "portion_size": 25.0, "unit": "г"},

    # Фрукти (1 порція ≈ 25 г вуглеводів)
    {"category": "fruits", "name": "Будь-які фрукти та ягоди", "portion_size": 300.0, "unit": "г"},
    {"category": "fruits", "name": "Банан", "portion_size": 150.0, "unit": "г"},
    {"category": "fruits", "name": "Манго", "portion_size": 180.0, "unit": "г"},
    {"category": "fruits", "name": "Хурма", "portion_size": 200.0, "unit": "г"},
    {"category": "fruits", "name": "Виноград", "portion_size": 180.0, "unit": "г"},
    {"category": "fruits", "name": "Фініки", "portion_size": 70.0, "unit": "г"},
]